### ISSUE TITLE
The shortcode appears below everything

### ISSUE THREAD

**Issue by digisphere** [digisphere/accessible-poetry#6]
try using print

**Comment by yehudah** [comment]
I didn't saw this issue but when a shortcode misbehave instead of echo or print the html you need to return the variable hold the html.
example:

<pre>
function my_shortcode() {
    $html = "<div>my html</div>";
   return $html;
} 
</pre>

**Comment by digisphere** [comment]
ye I know that.. I just had no time to update it. will do it today.. thanks again Yehuda :)
